<?php
// header('Access-Control-Allow-Origin: *');
// header('Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE');
// header('Access-Control-Allow-Headers: Content-type, X-Auth-Token, Oigirn, Authorization');
$apiKey = "rzp_test_oyvwo5SbELugd0";
$name = "Yash";
$email = "yashmodi622@gmail.com";
$amt = 100;
$phone = 7861048356;
?>
<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apiKey ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $amt*100 ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo 'PID_'.rand(10,100).'END' ?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Willty fitness"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://th.bing.com/th/id/OIG.Vbg4eHKxf0mEjkoEA1Za?pid=ImgGn"
    data-prefill.name="<?php echo $name ?>"
    data-prefill.email="<?php echo $email ?>"
    data-theme.color="#F37254"
>
console.log("hii");
</script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>